# Copyright (C) 2010-2021, Jason Colburne
#
# Not to be used in any form without express written consent.
# All rights reserved.
#
# $Id: makefile 19 2010-04-22 08:27:08Z jason $

LIBS       := red
LIBS.linux += pthread

include ../src.mk
