# Copyright (C) 2010, Redbeard Enterprises Ltd.
#
# Not to be used in any form without express written consent.
# All rights reserved.
#
# $Id: makefile 19 2010-04-22 08:27:08Z jason $

LIBS := red

include ../src.mk
