# Copyright (C) 2010-2021, Jason Colburne
#
# Not to be used in any form without express written consent.
# All rights reserved.
#
# $Id: makefile 21 2010-04-28 17:38:52Z jason $

LIBS := red

LIBS.linux = pthread rt

include ../src.mk
